.\" buildindex.1 -- 
.\" Copyright 1994 Rik Faith (faith@cs.unc.edu)
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 1, or (at your option) any
.\" later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" NOTE: This program is not distributed with any data.  This program
.\" operates on many different data types.  You are responsible for
.\" obtaining any data upon which this program operates.
.\" "
.TH BUILDINDEX 1 "4 December 1994" "" ""
.SH NAME
buildindex \- build an index file for the dict program
.SH SYNOPSIS
.BI "buildindex [\-Djdlr] " input_file
.SH DESCRIPTION
.B buildindex
takes as input dictionaries in various formats and output an index which is
compatibale with
.BR dict (1).
The index file has lines with the headword and offset separated by a tab
character.  The offset is in decimal.  The headword must not contain any
tab characters.  Each line ends with a newline.
.SH OPTIONS
.TP
.B -j
Assumes that the input file has the same format as the Jargon File.  That
is, all headwords are bracketed by ':' characters, and each entry ends on
the line prior to the next line that starts with a ':' character.
.sp
The Jargon File is available from prep.ai.mit.edu:/pub/gnu/jarg310.txt.gz
.TP
.B -d
Assumes that the input file has the same format as The Devil's Dictionary
(by Amrose Bierce), as distributed by the Internet Wiretap.  That is, all
headwords are in uppercase and end with a '.' or ',' character.  An entry
ends with a blank line prior to the beginning of the next entry.
.sp
The Devil's Dictionary is available from
wiretap.spies.com:/Library/Classic/devils.txt
.TP
.B -f
Assumes that the input file has the same format as the Free On-line
Dictionary of Computing (FOLDOC) from Denis Howe.  That is, all headwords
start in column one and have a newline before them.  All entries end with
the start of the next headword.
.sp
FOLDOC is available from wombat.doc.ic.ac.uk:/pub/Dictionary
.TP
.B -l
Assumes that headwords start in the first column and continue until some
non-space punctuation is encountered.  Entries end with a blank line.
.TP
.B -r
Reformats a file with the format described for
.BR \-l ,
inserting newlines in between entries.  This is necessary for
.BR dict (1),
since
.BR dict (1)
can't differentiate between the original format and other, similar formats.
Both
.B \-l
and
.B \-r
are for a latin dictionary that was posted to a newsgroup a long time ago.
It does not appear to be available on the net at this time.
.TP
.B -D
Turns on debugging.  This options probably doesn't do much.
.SH "SEE ALSO"
.BR dict (1)
.SH AUTHOR
The
.BR buildindex (1)
program was written by Rickard E. Faith (faith@cs.unc.edu) and is
distributable under the terms of the GNU General Public License.
.sp
The end-user is responsible for obtaining all data upon which this program
operates.  Please do not mail the author with requests for data.
