.TH DICTFMT_VIRTUAL 1 "January 15, 2003" "LINUX" "Linux User's Manual"
.SH NAME
dictfmt_virtual \- Uses dictfmt to create a virtual database file.
.SH SYNOPSIS
.B dictfmt_virtual 
.I [OPTIONS] 
.BI --db-list " <list>" 
.BI -s " name" 
.I dbbase 
.I [info_files...]
.SH DESCRIPTION
.B dictfmt_virtual
creates a 
.B dictd
database file representing a virtual dictionary database.
.SH OPTIONS
.TP
All options except --help and info_files are required.
.TP
.B --help
displays a usage message and exits
.TP
.BI --db-list " list"
list is a comma-separated list of the database names (as listed in 
.IR dictd.conf )
to be included in the virtual database.  If these databases are
located in a directory other than the default directory
(/usr/share/dictd/), a full pathname should be given. 
.TP
.BI -s " name"
name is the descriptive name to be used in the 00-database-short
header of the virtual database file.  
.TP
.B dbbase
the basename of the virtual database file to be created. 
.TP
.B info_files
an optional space-separated list of files containing additional
information to be inserted in the header of the virtual database file.
(This option is rarely necessary.)  If this option is included, it
must be given after all other options.
.SH AUTHOR
.B dictfmt_virtual 
was written by Aleksey Cheusov (vle@gmx.net).
.br
This manual page was written by Robert D. Hilliard <hilliard@debian.org>.
.SH "SEE ALSO"
.BR dictd (8),
.BR dictfmt (1)  
