.\" dict.1 -- 
.\" Copyright 1994, 1995 Rik Faith (faith@cs.unc.edu)
.\"
.\" This program is free software; you can redistribute it and/or modify it
.\" under the terms of the GNU General Public License as published by the
.\" Free Software Foundation; either version 1, or (at your option) any
.\" later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" NOTE: This program is not distributed with any data.  This program
.\" operates on many different data types.  You are responsible for
.\" obtaining any data upon which this program operates.
.\" "
.TH DICT 1 "23 August 1995" "" ""
.SH NAME
dict \- look up a definition in a dictionary
.SH SYNOPSIS
.BI "dict [\-DsSIaelhq] [ \-d " dictionary " ] [ " word " ]"
.br
.BI "dict [\-DsSIaelhq] [ \-f " filename " ] [ \-i " index " ] [ " word "]"
.br
.BI "dict [\-DsSIaelhq] [ \-u " filename " ] [ " word "]"
.SH DESCRIPTION
.B dict
looks up
.I word
in an on-line dictionary.
.B dict
looks up the word in a tab-delimited file of offsets, and then prints out
the entry from the dictionary file.  Several common dictionary file formats
are magically supported.
.PP
The index file has lines with the headword and offset separated by a tab
character.  The offset is in decimal.  The headword must not contain any
tab characters.  Each line ends with a newline.  Indices for several freely
available dictionaries (e.g., The Jargon File) can be automatically built
with the
.BR buildindex (1)
program.
.SH OPTIONS
.TP
.B \-s
Headword matching is usually exact, this option requests "substring"
matching.
.TP
.B \-S
If the headword is not found, possibilities are usually selected from those
words which have a Levenshtein distance (edit distance) of one.  This
option also includes words with a Soundex value that is identical to the
original word.
.TP
.BI "\-d " dictionary
Each dictionary in the dictionary database can be specified by using a
simple tag.  For example, if the dictionary database entry is "jargon
/usr/dict/jarg310.txt The Jargon File", then
.B \-d jargon
can be used to select this dictionary.
.B \-a
Specifies that all of the dictionaries in the database are to be searched,
until
.I word
is found in one of them.
.TP
.B \-e
Specifies that all of the dictionaries in the database are to be searched
(compare with the
.BR \-a " option)."
.TP
.B \-l
List the dictionary database.
.TP
.BI "\-u " filename
Usually, the dictionary database is loaded from "~/.dictrc" or from
"/etc/dictrc".  This option can be used to specify an alternative.
.TP
.B \-h
Provides help.
.TP
.B \-q
Quiet.  If present, the "description" field of the dictionary database is
printed before each dictionary entry.  This option suppresses that
information.
.TP
.BI "\-f " filename
Dictionary information is usually taken from a startup file.  For testing
purposes, the
.B \-f
option can be used to specify a dictionary path.  If the
.B \-i
option is not given, then the path to the index file is assumed to be the
same as
.I filename
with ".index" appended.
.TP
.BI "\-i " filename
This option specifies an alternate name for the index file.  See
.B \-f
for more information.
.TP
.B \-I
Specifies that
.B dict
will operate in "server mode."  This option is not currently implemented.
.TP
.B \-D
Turns on debugging.
.SH "THE DICTIONARY DATABASE"
The dictionary database is read from "~/.dictrc" or "/etc/dictrc" (if the
user's database file is missing.  The
.B \-u
option can override the defaults.
.PP
The dictionary database consists of lines with three white-space delimited
fields: the dictionary name, the path to the dictionary data, and a
description of the dictionary.  Lines starting with the "#" character in
the first column are ignored.  An example is:
.RS
.sp
jargon /usr/dict/jarg310.txt The Jargon File
.br
devils /usr/dict/devils.txt The Devil's Dictionary
.sp
.RE
For information on publically available dictionaries, please see
.BR buildindex (1).
Note that the index file is assumed to have the same name as the data file,
except that ".index" is appended to the path.
.SH "FILES"
.I ~/.dictrc
.br
.I /etc/dictrc
.br
.I /usr/dict
.SH "SEE ALSO"
.BR look (1),
.BR webster (1),
.BR buildindex (1),
.BR compressdict (1)
.SH AUTHOR
The
.BR dict (1)
program was written by Rickard E. Faith (faith@cs.unc.edu) and is
distributable under the terms of the GNU General Public License.
.sp
The end-user is responsible for obtaining all data upon which this program
operates.  Please do not mail the author with requests for data.
