#!/usr/bin/env bash

# Copyright (c) 2010
#    Alexander Vorontsov <vorontsov@imb.invention-machine.com>
#        Aleksey Cheusov <vle@gmx.net>
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

############################################################
# functions
#

function set_selection()
{
	selection=""

	selection=`$xclip_prog -utf8 -o`
	if test -z "$selection"; then
		exit
	fi
}

function set_geometry()
{
	# display resolution
	xD=1280
	yD=1024
	
	# popup window resolution
	xW=724
	yW=364

	geometry=""

	if test -n "$1" -a -n "$2"; then
		x="$1"
		y="$2"
		
		# adjust value of x
		if test "$x" -lt "$((xD/2))"; then
			if "$((xD))" -lt "$((x+xW))"; then
				x=$((x+5))
			else
				x="$((xD-xW-5))"
			fi
		else
			x=$((x-730))
		fi

		# adjust value of y
		if test "$y" -lt "512"; then
			y=$((y+5))
		else
			y=$((y-370))
		fi

		#geometry="-geometry 80x20+${x}+${y}"
		geometry="-geometry 80x20+200+200"
	fi
}

############################################################
# main
#

xclip_prog="xclip"

set_selection
set_geometry "$1" "$2"

tmp_dir="/tmp/`basename $0`.$$"
trap "rm -rf $tmp_dir" 0 1 2 3 15
mkdir -m 700 "$tmp_dir"

dictl -h "vorontsov" -d "Babylon_S_zh-en" "$selection" > "$tmp_dir/res_1.txt" &
dictl -h "syn-proc"  -d "xinsheng_zh-ru" "$selection" > "$tmp_dir/res_2.txt" &
wait

#dictl "$selection" |
cat $tmp_dir/res_*.txt |
grep -v "definition found" |
colorit -P - -c ~/.coloritrc/.coloritrc_dict |
sed 's/<[^ >]\+>//g' > "$tmp_dir/res.txt"

LANG=en_US.utf8 uxterm $geometry \
	-name "dict" \
	-title "dict"  \
	-fn -misc-fixed-medium-r-normal--18-120-100-100-c-90-iso10646-1 \
	-e "less -R < $tmp_dir/res.txt"
