#!/bin/sh

# Copyright (c) 2010
#    Alexander Vorontsov <vorontsov@imb.invention-machine.com>
#    Aleksey Cheusov     <vle@gmx.net>
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

############################################################
# Variables settable by user

XCLIP_PROG=${XCLIP_PROG-xclip}
XTERM_PROG=${XTERM_PROG-xterm}
UTF8_LOCALE=${UTF8_LOCALE-en_US.UTF-8}
DICT_PROG=${DICT_PROG-dict}
DICT_SERVER_OPT=${DICT_SERVER_OPT--h dictd.xdsl.by}
DICT_PORT_OPT=${DICT_PORT_OPT--p 2628}
DICT_DB_OPT=${DICT_PORT_OPT--d en-ru}
X_CLASS=${X_CLASS--class XTerm}
X_NAME=${X_NAME--name xterm_dict}
TITLE=${TITLE--title dict_lookup}

colorit_config=$HOME/.colorit.d/coloritrc_dict
if test -z "$COLORIZER"; then
    if test -f "$colorit_config"; then
	COLORIZER="colorit -P - -c $colorit_config"
    else
	COLORIZER=cat
    fi
fi

############################################################
# functions
#

set_selection ()
{
    selection=`$XCLIP_PROG -utf8 -o`
    if test -z "$selection"; then
	exit
    fi
}

set_geometry()
{
    # display resolution
    xD=1280
    yD=1024

    # popup window resolution
    xW=724
    yW=364

    geometry=""

    if test -n "$1" -a -n "$2"; then
	x="$1"
	y="$2"

	# adjust value of x
	if test "$x" -lt "$((xD/2))"; then
	    if "$((xD))" -lt "$((x+xW))"; then
		x=$((x+5))
	    else
		x="$((xD-xW-5))"
	    fi
	else
	    x=$((x-730))
	fi

	# adjust value of y
	if test "$y" -lt "512"; then
	    y=$((y+5))
	else
	    y=$((y-370))
	fi

	#geometry="-geometry 80x20+${x}+${y}"
	geometry="-geometry 80x20+200+200"
    fi
}

############################################################
# main
#

set_selection
set_geometry "$1" "$2"

tmp_dir="/tmp/`basename $0`.$$"
trap "rm -rf $tmp_dir" 0 1 2 3 15
mkdir -m 700 "$tmp_dir"

$DICT_PROG $DICT_SERVER_OPT $DICT_PORT_OPT $DICT_DB_OPT "$selection" \
    > "$tmp_dir/res_2.txt"

#dictl "$selection" |
cat $tmp_dir/res_*.txt |
grep -v "definition found" |
$COLORIZER > "$tmp_dir/res.txt"

unset LC_ALL || true
unset LANG || true
LC_CTYPE=$UTF8_LOCALE $XTERM_PROG $geometry \
    -u8 $X_CLASS $X_NAME $TITLE -e "less < $tmp_dir/res.txt"
