#!/bin/sh

# Copyright (c) 2010
#    Alexander Vorontsov <vorontsov@imb.invention-machine.com>
#    Aleksey Cheusov     <vle@gmx.net>
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

############################################################
# Variables settable by user

D_AWK_PROG=${D_AWK_PROG-awk}
D_XCLIP_PROG=${D_XCLIP_PROG-xclip}
D_XTERM_PROG=${D_XTERM_PROG-xterm}
D_UTF8_LOCALE=${D_UTF8_LOCALE-en_US.UTF-8}
D_DICT_PROG=${D_DICT_PROG-dict}
DICT_SERVER_OPT=${DICT_SERVER_OPT--h dictd.xdsl.by}
DICT_PORT_OPT=${DICT_PORT_OPT--p 2628}
DICT_DB_OPT=${DICT_DB_OPT--d en-ru}
XTERM_DICT_CLASS=${XTERM_DICT_CLASS--class XTerm}
XTERM_DICT_NAME=${XTERM_DICT_NAME--name xterm_dict}
XTERM_DICT_TITLE=${XTERM_DICT_TITLE--title dict_lookup}
TEXT_WIDTH=${TEXT_WIDTH-cyrillic_text_width}
D_TERM_X=${D_TERM_X-+200}
D_TERM_Y=${D_TERM_Y-+200}
D_TERM_H=${D_TERM_H-+40}
D_LESS_PROG=${D_LESS_PROG-less}

if test -z "$COLORIZER"; then
    colorit_config=$HOME/.colorit.d/dict
    if test -f "$colorit_config"; then
	COLORIZER="colorit -P - -c $colorit_config"
    else
	COLORIZER=cat
    fi
fi

############################################################
# functions
#

cyrillic_text_width (){
    # This function may not work properly for languages
    # other than Russian. wcwidth(3) and C language is needed!
    LC_ALL=C $D_AWK_PROG -v h="$D_TERM_H" '
	BEGIN {max = 15}
	{ gsub(/[\300-\337][\200-\277]/, "1")
	  sub(/ +$/, "")
	  curr=length($0)
	  if (curr > max) max=curr
	}
	END { print max "x" (NR < h ? NR : h)+1}' "$@"
}

set_query ()
{
    if test -n "$query"; then
	return 0
    fi
    query=`$D_XCLIP_PROG -o`
    if test -z "$query"; then
	exit
    fi
}

############################################################
# main
#

help (){
    cat 1>&2 <<'EOF'
usage: dict_lookup [OPTIONS]
   -h           display this help
   -x <x>       X coordinate of xterm
   -y <y>       Y coordinate of xterm
   -s <WxH>     size of xterm in symbols, e.g. 50x20
   -q <query>   query
EOF
}

while getopts x:y:s:q: f
do
    case $f in
	h)      help; exit 0;;
	x)      D_TERM_X=+$OPTARG;;
	y)      D_TERM_Y=+$OPTARG;;
	s)      TERM_WH=$OPTARG;;
	q)      query=$OPTARG;;
	'?')    help; exit 1;;
    esac
done
shift `expr $OPTIND - 1`

set_query

tmp_dir="/tmp/`basename $0`.$$"
trap "rm -rf $tmp_dir" 0 1 2 3 15
mkdir -m 700 "$tmp_dir"

$D_DICT_PROG $DICT_SERVER_OPT $DICT_PORT_OPT $DICT_DB_OPT "$query" 2>&1 |
env LC_ALL=C grep -Ev "definitions? found" > "$tmp_dir/res.txt"

if test -z "$TERM_WH"; then
    TERM_WH=`$TEXT_WIDTH "$tmp_dir/res.txt"`
fi

geometry="-geometry ${TERM_WH}${D_TERM_X}${D_TERM_Y}"

unset LC_ALL || true
unset LANG || true
LC_CTYPE=$D_UTF8_LOCALE $D_XTERM_PROG $geometry \
    -u8 $X_CLASS $XTERM_DICT_NAME $XTERM_DICT_TITLE \
    -e "$COLORIZER < $tmp_dir/res.txt | $D_LESS_PROG"
